server:
  port: 7001
  servlet:
    context-path: /yuan

spring:
  application:
    name: yuan-share

    #解决swagger Failed to start bean 'documentationPluginsBootstrapper' 的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # thymeleaf
  thymeleaf:
    #缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
    # 开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML

    #mmm
    prefix: classpath:/templates/
    suffix: .html

  #    resources:
  #      static-locations: classpath:/static/
  #    mvc:
  #      static-path-patten: /static/**

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lu_tale?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&useInformationSchema=true
    username: root
    password: hsp
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        # 配置允许哪IP地址可以访问，''表示所有
        allow: ''
      web-stat-filter:
        enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,classpath:mapper/**/*Mapper.xml
  # Mybatis 返回map 类型 ，当数据库字段值为空时，不显示字段问题配置，true：显示值为空的字段
  configuration:
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: input

# springfox配置，解决访问接口文档地址（http://localhost:7001/yuan/doc.html)时，出现错误
springfox:
  documentation:
    open-api:
      v3:
        path: /${spring.application.name}/v3/api.docs